#!/bin/sh --login
#Robert Grumbine
# variously through 11 September 2018
#Note: The --login is critical for being able to run non-interactively

#set -x

############## Module (environment) Management #################

# all this moved out to the runup script

module list

###############################################################

#Set up something like sms environment for calling J job
export cyc=${cyc:-00}
export net=omb
export envir=fv3
export code_ver=v5.0.7
export vessel_icing_ver=$code_ver
export job=vessel_icing
export SMSBIN=/u/Robert.Grumbine/para/${job}.${code_ver}/sms/
export NWROOT=/u/Robert.Grumbine/para/

#Now call J job, which will call the ex
/u/Robert.Grumbine/para/${job}.${code_ver}/jobs/JSICE.$envir
